auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: aluan.github.com
url: http://aluan.github.com
feed: /atom.xml
author_info: <a href="http://aluan.github.com/">Aluan</a>
